[package]
name = "uac"
version = "0.0.0"
edition = "2021"

[dependencies.windows]
version = "0.39.0"
features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Console",
    "Win32_System_Environment",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
]
