format_code_in_doc_comments = true
format_macro_matchers = true
hex_literal_case = "Upper"
imports_layout = "Vertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
